[tool.poetry]
name = "fluxrun"
version = "v1.4.1"
description = "Python wrapper for EddyPro flux calculations"
authors = ["holukas <lukas.hoertnagl@usys.ethz.ch>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.3"
PyQt5 = "^5.15.9"
matplotlib = "^3.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
