__version__ = "1.0"
__date__ = "XX XXX 2021"
__link_source_code__ = "https://gitlab.ethz.ch/holukas/fluxrun"
__link_releases__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/releases"
__link_wiki__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/wikis/home"
__license__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/blob/master/LICENSE"
__ep_version__ = "7.0.7"
__link_ep_changelog__ = "https://www.licor.com/env/support/EddyPro/topics/whats-new.html"
