__version__ = "0.5.0"
__date__ = "16 Mar 2021"
__link_source_code__ = "https://gitlab.ethz.ch/holukas/fluxrun"
__link_releases__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/releases"
__link_wiki__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/wikis/home"
__license__ = "https://gitlab.ethz.ch/holukas/fluxrun/-/blob/master/LICENSE"
