__version__ = "1.1"
__date__ = "4 Nov 2022"
__link_source_code__ = "https://gitlab.ethz.ch/flux/fluxrun"
__link_releases__ = "https://gitlab.ethz.ch/flux/fluxrun/-/releases"
__link_changelog__ = "https://gitlab.ethz.ch/flux/fluxrun/-/blob/master/CHANGELOG.md"
__license__ = "https://gitlab.ethz.ch/flux/fluxrun/-/blob/master/LICENSE"
__ep_version__ = "7.0.9"
__link_ep_changelog__ = "https://www.licor.com/env/support/EddyPro/topics/whats-new.html"
