# Use forward-slash for paths /

SITE: "CH-FRU"
RAWDATA:
  INDIR: "F:/Sync/luhk_work/CURRENT/FRU_rECord_test/IN"
  COMPRESSION: "gzip"
  HEADER_FORMAT: "4-row header (rECord files)"
  FILENAME_DATETIME_FORMAT: "ec_yyyymmdd-HHMM"
  START_DATE: "2023-12-31 01:00"
  END_DATE: "2025-12-31 23:59"
  PARSING_STRING: "TODO2"
FLUX_PROCESSING:
  EDDYPRO_PROCESSING_FILE: "F:/Sync/luhk_work/CURRENT/FRU_rECord_test/updated_settings.eddypro"

OUTPUT:
  OUTDIR: "F:/TMP/d"
  PLOT_RAWDATA_AVAILABILITY: 1
  PLOT_RAWDATA_AGGREGATES: 1
  PLOT_SUMMARY: 1
  DELETE_UNCOMPRESSED_ASCII_AFTER_PROCESSING: 0

## OUTPUT
## ======
#_run_id=FR-20250401-135040
#_dir_out_run=F:/TMP/d/CH-FRU_FR-20250401-135040
#_dir_out_run_log=F:/TMP/d/CH-FRU_FR-20250401-135040/0_log
#_dir_out_run_rawdata_ascii_files=F:/TMP/d/CH-FRU_FR-20250401-135040/1-0_rawdata_files_ascii
#_dir_used_rawdata_ascii_files_eddypro_data_path=F:/TMP/d/CH-FRU_FR-20250401-135040/1-0_rawdata_files_ascii
#_dir_out_run_plots_availability_rawdata=F:/TMP/d/CH-FRU_FR-20250401-135040/1-1_rawdata_plots_availability
#_dir_out_run_plots_aggregates_rawdata=F:/TMP/d/CH-FRU_FR-20250401-135040/1-2_rawdata_plots_aggregates
#_dir_out_run_eddypro=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations
#_dir_out_run_eddypro_ini=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/ini
#_dir_out_run_eddypro_bin=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/bin
#_dir_out_run_eddypro_results=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/results
#_dir_out_run_plots_summary=F:/TMP/d/CH-FRU_FR-20250401-135040/2-1_eddypro_flux_calculations_summary_plots
#
##rawdata_indir=
##rawdata_file_compression=gzip
##rawdata_header_format=
##rawdata_filename_datetime_format=
##rawdata_start_date=
##rawdata_end_date=
##rawdata_sitefiles_parse_str=XXX
## _sitefiles_search_str=CH-FRU_*.csv.gz
## _sitefiles_parse_str=CH-FRU_ec_%Y%m%d-%H%M.csv.gz
##path_selected_eddypro_processing_file=F:/Sync/luhk_work/CURRENT/FRU_rECord_test/updated_settings.eddypro
##plot_availability_rawdata=1
##plot_aggregates_rawdata=0
##plot_summary=1
##delete_uncompressed_ascii_after_processing=0
##dir_out=F:/TMP/d
#
#
#_path_used_eddypro_processing_file=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/ini/processing.eddypro
#_path_found_eddypro_metadata_file=F:/Sync/luhk_work/CURRENT/FRU_rECord_test/updated_settings.eddypro
#_path_used_eddypro_metadata_file=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/ini/updated_settings.metadata
#_path_used_eddypro_app_rp=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/bin/eddypro_rp.exe
#_path_used_eddypro_app_fcc=F:/TMP/d/CH-FRU_FR-20250401-135040/2-0_eddypro_flux_calculations/bin/eddypro_fcc.exe
#
## _SCRIPT
## =======
#_dir_root=F:/Sync/luhk_work/20 - CODING/23 - FLUX
#_dir_fluxrun=F:/Sync/luhk_work/20 - CODING/23 - FLUX/fluxrun
#_dir_script=F:/Sync/luhk_work/20 - CODING/23 - FLUX/fluxrun/fluxrun
#_dir_settings=F:/Sync/luhk_work/20 - CODING/23 - FLUX/fluxrun/fluxrun/settings

