RAWDATA:
  INDIR: F:/CURRENT/LAE_FP2025/2021_1/1-BICO/CH-LAE_2021_1_BICO-20250520-174356/raw_data_ascii
  FILENAME_ID: CH-LAE_yyyymmddHHMM.csv.gz
  HEADER_FORMAT: 3-row header (bico files)
  START_DATE: 2020-12-31 00:00
  END_DATE: 2021-12-31 23:59
  PLOT_RAWDATA_AVAILABILITY: 1
  PLOT_RAWDATA_AGGREGATES: 1
FLUX_PROCESSING:
  RUN_FLUX_CALCS: 1
  EDDYPRO_PROCESSING_FILE: F:/CURRENT/LAE_FP2025/2021_1/2-FLUXRUN/CH-LAE_2021_1_[IRGA72]_HS50-B_IRGA72-A_OPENLAG.eddypro
OUTPUT:
  OUTDIR: F:/CURRENT/LAE_FP2025/2021_1/2-FLUXRUN
  OUTDIR_PREFIX: 2021_1xxx
  PLOT_SUMMARY: 1
AFTER PROCESSING:
  DELETE_UNCOMPRESSED_ASCII_AFTER_PROCESSING: 0
