__version__ = "2.0.2"
__date__ = "14 Apr 2025"
__link_source_code__ = "https://github.com/holukas/fluxrun"
__link_releases__ = "https://github.com/holukas/fluxrun/releases"
__link_changelog__ = "https://github.com/holukas/fluxrun/blob/master/CHANGELOG.md"
# __license__ = "https://gitlab.ethz.ch/flux/fluxrun/-/blob/master/LICENSE"
__ep_version__ = "7.0.9"
__link_ep_changelog__ = "https://www.licor.com/env/support/EddyPro/topics/whats-new.html"
